baseURL = "https://Chic0s.fr"
languageCode = "fr"
theme = "terminal"
title = "Chic0s"
paginate = 5

[params]
  # Répertoire principal du contenu
  contentTypeName = "posts"

  # Couleur de base du thème (sera overridée par style.css)
  themeColor = "white"

  # Pleine largeur
  fullWidthTheme = true
  centerTheme = false

  # Auteur
  author = "Chic0s"
  windowTitle = "Chic0s"

  # Nombre de posts sur la homepage
  amountNewsOnHomepage = 5

  # Format de date
  dateFormat = "02/01/2006"

[params.logo]
  logoText = "[Chic0s]"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "htb"
    name = "HTB"
    url = "/posts/htb/"
    weight = 10

  [[menu.main]]
    identifier = "ctf"
    name = "CTF"
    url = "/posts/ctf/"
    weight = 20

  [[menu.main]]
    identifier = "dojo"
    name = "Dojo YWH"
    url = "/posts/dojo/"
    weight = 30

  [[menu.main]]
    identifier = "hardware"
    name = "Hardware"
    url = "/posts/hardware/"
    weight = 40

  [[menu.main]]
    identifier = "sensibilisation"
    name = "Sensibilisation"
    url = "/sensibilisation/"
    weight = 50

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 60

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Activer le HTML inline dans le markdown
[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[markup.highlight]
  noClasses = false

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
